import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  content: { padding: 18, paddingTop: 12 },
  muted: { color: '#7f6c61', fontSize: 14 },
  primaryButton: { backgroundColor: '#795948', paddingVertical: 15, alignItems: 'center', marginTop: 10, borderRadius: 5 },
  primaryButtonText: { color: '#fffaf7', fontSize: 15, fontWeight: '700' },
  choiceGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  choice: { width: '48%', backgroundColor: '#fff', borderWidth: 1, borderColor: '#ebdfd6', borderRadius: 10, padding: 14, marginBottom: 12 },
  choiceActive: { backgroundColor: '#f7efe9', borderColor: '#916e5c' },
  choiceTitle: { fontSize: 15, fontWeight: '700', color: '#56453f' },
  choiceTitleActive: { color: '#5d3d31' },
  choiceSubtitle: { marginTop: 6, color: '#877267', fontSize: 12 },
  choiceSubtitleActive: { color: '#6d4e3f' },
  sectionTitle: { flexDirection: 'row', alignItems: 'center', marginTop: 18, marginBottom: 10 },
  sectionNumber: { width: 28, color: '#9d7b67', fontWeight: '700', fontSize: 12 },
  sectionText: { fontSize: 15, fontWeight: '700', color: '#463831' },
  horizontal: { paddingBottom: 8 },
  dateChip: { marginRight: 10, backgroundColor: '#fff', borderWidth: 1, borderColor: '#e7d7cc', borderRadius: 16, paddingHorizontal: 12, paddingVertical: 10 },
  dateChipActive: { backgroundColor: '#7b5845', borderColor: '#7b5845' },
  dateChipText: { color: '#5a4034', fontWeight: '600' },
  dateChipTextActive: { color: '#fffaf7' },
  times: { flexDirection: 'row', flexWrap: 'wrap' },
  timeChip: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#eadbd1', borderRadius: 16, paddingHorizontal: 12, paddingVertical: 8, marginRight: 8, marginBottom: 8 },
  timeChipActive: { backgroundColor: '#7b5845', borderColor: '#7b5845' },
  timeChipText: { color: '#5d463e', fontWeight: '600' },
  timeChipTextActive: { color: '#fffaf7' },
  summary: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#eadbd1', borderRadius: 10, padding: 16, marginTop: 18 },
  summaryTitle: { color: '#3f312d', fontSize: 18, fontWeight: '700' },
  summaryText: { color: '#6b5a52', marginTop: 6, fontSize: 14 },
});