import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#fffaf7' },
  grow: { flex: 1 },
  authContent: { padding: 24, paddingBottom: 48, flexGrow: 1, justifyContent: 'center' },
  brand: { alignItems: 'center', marginBottom: 36 },
  brandMark: { width: 70, height: 70, borderRadius: 35, borderWidth: 1, borderColor: '#b79680', alignItems: 'center', justifyContent: 'center', marginBottom: 8 },
  brandLeaf: { fontFamily: 'serif', color: '#9f7b64', fontSize: 38 },
  brandName: { fontFamily: 'serif', fontSize: 42, color: '#725849', letterSpacing: 1 },
  brandTagline: { fontSize: 10, color: '#9f7b64', letterSpacing: 2, marginTop: 4 },
  authCard: { backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#eadbd1', padding: 20, borderRadius: 8 },
  segment: { flexDirection: 'row', backgroundColor: '#f6eee9', padding: 3, borderRadius: 6, marginBottom: 18 },
  segmentItem: { flex: 1, alignItems: 'center', paddingVertical: 10, borderRadius: 4 },
  segmentItemActive: { backgroundColor: '#ffffff' },
  segmentText: { color: '#8c7669', fontSize: 14 },
  segmentTextActive: { color: '#654c3e', fontWeight: '700' },
  field: { marginBottom: 14 },
  fieldLabel: { color: '#9a7a67', fontSize: 10, fontWeight: '700', letterSpacing: 1.1, marginBottom: 7 },
  input: { borderBottomWidth: 1, borderColor: '#d8c5ba', color: '#3f352f', fontSize: 16, paddingVertical: 9 },
  inputInvalid: { borderColor: '#c4473a' },
  inputValid: { borderColor: '#3b9b69' },
  addressSuggestions: { maxHeight: 180, marginTop: -6, marginBottom: 12, borderWidth: 1, borderColor: '#ddd0c3', borderRadius: 6, backgroundColor: '#fff' },
  addressSuggestion: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#eee5df' },
  addressSuggestionText: { color: '#4e4e4e', fontSize: 14 },
  addressWarning: { color: '#945d10', fontSize: 12, marginTop: -8, marginBottom: 10 },
  addressAttribution: { color: '#6b5a52', fontSize: 10, marginTop: -8, marginBottom: 12 },
  primaryButton: { backgroundColor: '#795948', paddingVertical: 15, alignItems: 'center', marginTop: 10, borderRadius: 5 },
  primaryButtonText: { color: '#fffaf7', fontSize: 15, fontWeight: '700' },
  serverLink: { color: '#876a59', textAlign: 'center', marginTop: 22, fontSize: 13 },
  serverBox: { padding: 16, marginTop: 18, backgroundColor: '#f8f0eb', borderRadius: 6 },
  textButton: { marginTop: 10 },
  textButtonLabel: { color: '#75523f', fontWeight: '700', fontSize: 14 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(38, 28, 23, 0.5)', justifyContent: 'center', alignItems: 'center', padding: 24 },
  linkDialog: { width: '100%', maxWidth: 420, backgroundColor: '#fffaf7', borderRadius: 10, padding: 22, borderWidth: 1, borderColor: '#eadbd1' },
  linkDialogTitle: { color: '#45352e', fontSize: 19, fontWeight: '700', marginBottom: 10 },
  linkDialogMessage: { color: '#6f5c52', fontSize: 15, lineHeight: 22 },
  linkDialogActions: { flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', marginTop: 22, gap: 10 },
  linkCancelButton: { paddingVertical: 11, paddingHorizontal: 14 },
  linkCancelText: { color: '#795948', fontSize: 14, fontWeight: '600' },
  linkConfirmButton: { backgroundColor: '#795948', borderRadius: 5, paddingVertical: 11, paddingHorizontal: 16 },
  linkConfirmText: { color: '#fffaf7', fontSize: 14, fontWeight: '700' },
});