import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  content: { padding: 18, paddingTop: 12 },
  profileCard: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#efe2d8', borderRadius: 10, padding: 18, alignItems: 'stretch', marginBottom: 16 },
  profileHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 8 },
  avatar: { width: 60, height: 60, borderRadius: 30, backgroundColor: '#f0e0d6', alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
  avatarImage: { width: 60, height: 60, borderRadius: 30 },
  avatarText: { color: '#6c4d3d', fontSize: 22, fontWeight: '700' },
  profileName: { flex: 1, color: '#44332d', fontSize: 21, fontWeight: '700', marginBottom: 0 },
  editIconButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#f8f0eb', alignItems: 'center', justifyContent: 'center' },
  editIcon: { color: '#75523f', fontSize: 23, fontWeight: '700' },
  muted: { color: '#7f6c61', fontSize: 14 },
  profileFields: { width: '100%', marginTop: 12 },
  profileGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 4 },
  profileData: { width: '50%', paddingVertical: 10, paddingRight: 10, borderBottomWidth: 1, borderBottomColor: '#f1e7e0' },
  profileDataWide: { width: '100%' },
  dataLabel: { color: '#9a7a67', fontSize: 11, fontWeight: '700', marginBottom: 4 },
  dataValue: { color: '#51443d', fontSize: 14 },
  photoButton: { alignSelf: 'flex-start', paddingVertical: 8 },
  photoButtonText: { color: '#75523f', fontWeight: '700', fontSize: 14 },
  field: { marginBottom: 12 },
  fieldLabel: { color: '#9a7a67', fontSize: 12, fontWeight: '700', marginBottom: 4 },
  serverBox: { padding: 16, marginTop: 18, backgroundColor: '#f8f0eb', borderRadius: 6 },
  input: { borderBottomWidth: 1, borderColor: '#d8c5ba', color: '#3f352f', fontSize: 16, paddingVertical: 9 },
  profileActions: { width: '100%', flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', gap: 10, marginTop: 12 },
  secondaryButton: { paddingVertical: 12, paddingHorizontal: 14, borderRadius: 6, backgroundColor: '#eee4dc' },
  secondaryButtonText: { color: '#69574f', fontWeight: '700' },
  saveButton: { alignSelf: 'center', paddingVertical: 13, paddingHorizontal: 16, borderRadius: 6, backgroundColor: '#795948', alignItems: 'center' },
  saveButtonText: { color: '#fffaf7', fontSize: 14, fontWeight: '700' },
  error: { color: '#a33e35', fontSize: 13, marginTop: 8 },
  success: { color: '#15803d', fontSize: 13, marginTop: 8 },
  textButton: { marginTop: 10 },
  textButtonLabel: { color: '#75523f', fontWeight: '700', fontSize: 14 },
  logoutButton: { marginTop: 18, borderWidth: 1, borderColor: '#d9a89e', backgroundColor: '#fff2ef', paddingVertical: 14, borderRadius: 8, alignItems: 'center' },
  logoutText: { color: '#9a4c41', fontWeight: '700', fontSize: 15 },
  deleteButton: { marginTop: 10, borderWidth: 1, borderColor: '#d9a89e', paddingVertical: 13, borderRadius: 8, alignItems: 'center' },
  deleteText: { color: '#9a4c41', fontWeight: '700', fontSize: 14 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(38, 28, 23, 0.5)', justifyContent: 'center', alignItems: 'center', padding: 24 },
  deleteDialog: { width: '100%', maxWidth: 420, backgroundColor: '#fffaf7', borderRadius: 10, padding: 22, borderWidth: 1, borderColor: '#eadbd1' },
  deleteDialogTitle: { color: '#45352e', fontSize: 19, fontWeight: '700', marginBottom: 10 },
  deleteDialogMessage: { color: '#6f5c52', fontSize: 15, lineHeight: 22 },
  deleteDialogActions: { flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', marginTop: 22, gap: 10, flexWrap: 'wrap' },
  deleteCancelButton: { paddingVertical: 11, paddingHorizontal: 14 },
  deleteCancelText: { color: '#795948', fontSize: 14, fontWeight: '600' },
  deleteConfirmButton: { backgroundColor: '#a33e35', borderRadius: 5, paddingVertical: 11, paddingHorizontal: 16 },
  deleteConfirmText: { color: '#fffaf7', fontSize: 14, fontWeight: '700' },
});